### ISSUE TITLE
Error in Multi-Job Submission

### ISSUE THREAD

**Issue by Mythologos** [bdusell/qfunnel#9]
I was using a Python script to generate and run multiple jobs. The script would create multiple deferred job submissions before running one `qf check` at the end to fill queues. After the first job was successfully submitted, I received the following error:

```
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/bin/qf", line 8, in <module>
    sys.exit(main())
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/lib/python3.8/site-packages/qfunnel/cli.py", line 174, in main
    program.check()
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/lib/python3.8/site-packages/qfunnel/program.py", line 124, in check
    self.check_impl(conn)
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/lib/python3.8/site-packages/qfunnel/program.py", line 217, in check_impl
    while self.try_dequeue_one(conn):
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/lib/python3.8/site-packages/qfunnel/program.py", line 246, in try_dequeue_one
    if limit is None or self.queue_has_open_slots(queue, limit):
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/lib/python3.8/site-packages/qfunnel/program.py", line 257, in queue_has_open_slots
    for job in self.enumerate_own_backend_jobs_in_queue(queue):
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/lib/python3.8/site-packages/qfunnel/program.py", line 269, in enumerate_own_backend_jobs_in_queue
    for job in self.backend.get_own_pending_jobs()
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/lib/python3.8/site-packages/qfunnel/real_backend.py", line 61, in get_own_pending_jobs
    return [dict_to_job(job) for job in pending_jobs]
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/lib/python3.8/site-packages/qfunnel/real_backend.py", line 61, in <listcomp>
    return [dict_to_job(job) for job in pending_jobs]
  File "/afs/crc.nd.edu/user/s/sbothwel/.local/lib/python3.8/site-packages/qfunnel/real_backend.py", line 108, in dict_to_job
    queue=d['queue_name'] or d['hard_req_queue'],
KeyError: 'hard_req_queue'
```

The error did not stop jobs from being properly submitted nor cause any known issues. However, it happened upon the submission of every second job for every use of `qf check`.

**Comment by bdusell** [comment]
Was the queue full at the time, i.e. was the job in the qw state? Or was the job able to go into the r state right away?

**Comment by Mythologos** [comment]
The queue was not full at the time. There was space, and the jobs could have gone into the r state right away. I don't remember ever seeing a qw state when I was handling the issue.

**Comment by bdusell** [comment]
The XML API from qstat changed when the CRC updated its software over the break. I've updated qfunnel accordingly.
